### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [pasdam/wikisearch#1]
It would be neat to have this available on F-Droid. Would that be possible?

**Comment by pasdam** [comment]
Yes, if you want you can use it

**Comment by pizzamaker** [comment]
But I mean, it would be good to have it distributed through F-Droid. Would you be interested in helping out? Here's how: https://f-droid.org/contribute/

**Comment by pasdam** [comment]
Thanks for your interest, but the project is pretty old and outdated, and I don't have time to update it, sorry. But feel free to use it, anyway you want.
